# Site settings
title: C# Lesson Exercises
email: contact@evilham.com
description: >
  Rendered exercise descriptions for the C# lessons
baseurl: "/csharp-lessons"
url: "https://evilham.github.io/"
slides_url: https://evilham.com/media/csharp/de
twitter_username: CyborgEvilham
github_username: evilham

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .c9/
  - .git/
  - latex/

defaults:
  -
    scope:
      path: ""
      type: "exercises"
    values:
      layout: "exercise"

collections:
  exercises:
    output: true
